package main.java.app.hgm.product;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import main.java.app.hgm.chapter.ChapterVO;
import org.springframework.beans.factory.annotation.Autowired;

public interface ProductMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int deleteByPrimaryKey(Integer sn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insert(ProductVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int insertSelective(ProductVO record);

    
    List<ProductVO> selectByExample(ProductExample example);

   // List<ChapterVO> selChapterList(String leccode);
    
    ProductVO selectByPrimaryKey(Integer sn);

    
    int updateByExampleSelective(@Param("record") ProductVO record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByExample(@Param("record") ProductVO record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKeySelective(ProductVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table career
     *
     * @mbg.generated Tue Dec 17 11:09:48 KST 2019
     */
    int updateByPrimaryKey(ProductVO record);
}